feat: Update install script and zsh configurations
- Add force option to `rm` commands in install script for `.zshrc` and new `.zshenv`
- Create symlink for new `.zshenv` file in user's home directory
- Update Homebrew installation command to append to `.zprofile` without a space
- Refine condition check formatting and error handling in composer installation section
- Remove unnecessary spaces in quicklook plugins installation command
- Update `droid` alias in `.aliases` to include a specific window title
- Introduce new `.zshenv` file for setting environment variables and configurations
- Consolidate environment and path configurations in `.zshenv`, removing duplications from `.zshrc`
- Clean up `.zshrc` by removing outdated comments and unused configurations

diff --git a/installscript b/installscript
--- a/installscript
+++ b/installscript
@@ -14,8 +14,10 @@ ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
 git config --global core.excludesfile $HOME/.global-gitignore
 
 # Symlink zsh prefs
-rm $HOME/.zshrc
+rm -f $HOME/.zshrc
 ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
+rm -f $HOME/.zshenv
+ln -s $HOME/.dotfiles/shell/.zshenv $HOME/.zshenv
 
 # Symlink vim prefs
 rm $HOME/.vimrc
@@ -45,7 +47,7 @@ echo '----------------'
 echo install homebrew
 sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
-echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
+echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>$HOME/.zprofile
 eval "$(/opt/homebrew/bin/brew shellenv)"
 
 echo 'Install node'
@@ -86,7 +88,7 @@ brew install git-secret
 
 echo 'Install some nice quicklook plugins'
 echo '-----------------------------------'
-brew install --cask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzip  suspicious-package
+brew install --cask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzip suspicious-package
 
 echo 'Install php'
 echo '-----------'
@@ -99,9 +101,8 @@ echo '----------------'
 EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
 php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
 ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
-if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
-then
-    >&2 echo 'ERROR: Invalid installer checksum'
+if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]; then
+    echo >&2 'ERROR: Invalid installer checksum'
     rm composer-setup.php
     exit 1
 fi
